k8s/base/tekton/resources/task-generate-cyclonedx.yaml
k8s/base/tekton/resources/task-generate-domino.yaml
src/main/java/org/redhat/sbomer/model/Sbom.java
src/main/java/org/redhat/sbomer/processor/PncArtifactsToSbomPedigreeProcessor.java
src/main/java/org/redhat/sbomer/processor/PncToSbomPedigree.java
src/main/java/org/redhat/sbomer/rest/v1alpha1/SBOMResource.java
src/main/java/org/redhat/sbomer/service/SBOMService.java
src/main/java/org/redhat/sbomer/utils/Constants.java
src/main/java/org/redhat/sbomer/utils/SbomUtils.java
src/main/java/org/redhat/sbomer/utils/enums/SbomType.java
src/test/java/org/redhat/sbomer/test/TestSBOMService.java
src/test/java/org/redhat/sbomer/test/TestSbomRepository.java
src/test/resources/payloads/payload-invalid-bom.json
src/test/resources/payloads/payload-valid.json
src/test/resources/sboms/sbom-valid-enriched-v10.json
src/test/resources/sboms/sbom-valid-parent.json

- Add the type to SBOM
- Implement new enrichment processor based on Sbom pedigree, and make it the default processor

New enrichment processor based on Sbom pedigree (stripped version of https://github.com/project-ncl/sbomer/pull/16)

---

hack/internal-build-image.sh

It looks that after last refactoring of scripts I introduced a bug in Minikube image generation.

ci(hack): fix minikube image generation

---

core/src/main/java/org/jboss/sbomer/core/utils/UrlUtils.java
service/src/main/java/org/jboss/sbomer/messaging/UmbMessageConsumer.java
service/src/main/java/org/jboss/sbomer/model/Sbom.java
service/src/main/java/org/jboss/sbomer/rest/v1alpha1/SBOMResource.java
service/src/main/java/org/jboss/sbomer/service/SbomRepository.java
service/src/main/java/org/jboss/sbomer/service/SbomService.java
service/src/main/resources/application.yaml
service/src/test/java/org/jboss/sbomer/test/SBOMResourceTest.java
service/src/test/java/org/jboss/sbomer/test/TestSbomRepository.java
service/src/test/resources/payloads/payload-invalid-bom.json
service/src/test/resources/payloads/payload-valid.json
service/src/test/resources/sboms/sbom-valid-enriched-v10.json
service/src/test/resources/sboms/sbom-valid-parent.json

- Add rootPurl identifier to Sbom model
- Retrieve base and enriched sboms with buildId and rootPurl
- Add tests and fix test resources 
- Add a flag to enable or disable UMB consumers and producers

[NCL-7696] - Add rootPurl identifier to Sbom model and add endpoints

---

cli/src/main/java/org/jboss/sbomer/cli/commands/generator/CycloneDXPluginMavenGenerateCommand.java
cli/src/main/java/org/jboss/sbomer/cli/commands/generator/DominoMavenGenerateCommand.java
cli/src/main/java/org/jboss/sbomer/cli/commands/processor/AbstractProcessCommand.java
cli/src/main/java/org/jboss/sbomer/cli/commands/processor/DefaultProcessCommand.java
cli/src/main/java/org/jboss/sbomer/cli/commands/processor/RedHatProductProcessCommand.java
core/src/main/java/org/jboss/sbomer/core/errors/ErrorResponse.java
service/src/main/java/org/jboss/sbomer/features/umb/consumer/UmbMessageConsumer.java
service/src/main/java/org/jboss/sbomer/features/umb/producer/UmbMessageProducer.java
service/src/main/java/org/jboss/sbomer/k8s/TaskRunStatusHandler.java
service/src/main/java/org/jboss/sbomer/rest/errors/ClientExceptionMapper.java
service/src/main/java/org/jboss/sbomer/rest/errors/DefaultExceptionMapper.java
service/src/main/java/org/jboss/sbomer/rest/errors/RSQLExceptionMapper.java
service/src/main/java/org/jboss/sbomer/runtime/ApplicationLifecycle.java
service/src/main/java/org/jboss/sbomer/runtime/LoggingFilter.java

- Creation, Updating, Accessing or Deletion of restricted data classifications
- Application or process startup, shutdown or restart
- Initiation of accepting a network connection along with IP Address captured

[NCL-7867] Log Event Of Interest

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/auto/GenerateConfigCommand.java
core/src/main/java/org/jboss/sbomer/core/features/sbom/config/runtime/Config.java
k8s/components/tekton/resources/task-init.yaml
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/GenerationRequest.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/GenerationRequestBuilder.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/GenerationRequestFluent.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/GenerationRequestFluentImpl.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/GenerationRequestReconciler.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/model/SbomGenerationRequest.java
service/src/main/resources/db-update/00006-1.0.1.sql

Now we are providing more information on the reason why the initialization phase (config generation filed). This is first step in providing detailed information.
https://issues.redhat.com/browse/NCL-7967

feat: provide more information for failed initialization phase

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/auto/GenerateCommand.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/auto/GenerateConfigCommand.java
core/src/main/java/org/jboss/sbomer/core/features/sbom/enums/GenerationResult.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/GenerationRequest.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/GenerationRequestBuilder.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/GenerationRequestFluentImpl.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/GenerationRequestReconciler.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/model/SbomGenerationRequest.java
service/src/main/resources/db-update/00007-1.0.1.sql
service/src/test/java/org/jboss/sbomer/service/test/feature/sbom/k8s/reconciler/GenerationPhaseGenerationRequestReconcilerTest.java
service/src/test/java/org/jboss/sbomer/service/test/feature/sbom/k8s/reconciler/GenerationRequestReconcilerTest.java
service/src/test/java/org/jboss/sbomer/service/test/feature/sbom/k8s/reconciler/InitializationPhaseGenerationRequestReconcilerTest.java
service/src/test/resources/configs/multi-product.yaml

https://issues.redhat.com/browse/NCL-7994

Set generation request failed reason according to generation outcome

---

service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/GenerationRequestReconciler.java

This ensures that the the correct values are set always

fix: use the common method to set statuses

---

cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/ConfigReaderIT.java
cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/command/processor/DefaultProcessCommandIT.java
hack/run-service-dev.sh
pom.xml
service/pom.xml
service/src/main/java/org/jboss/sbomer/service/feature/sbom/rest/rsql/RSQLProducerImpl.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/SbomGenerationRequestRSQLProducer.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/SbomRSQLProducer.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/k8s/reconciler/GenerationPhaseGenerationRequestReconcilerIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/k8s/reconciler/InitializationPhaseGenerationRequestReconcilerIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/messaging/GenerationFinishedMessageBodyIT.java

Upgrade to Quarkus 3.3

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/GradleCycloneDxGenerateCommand.java
core/src/main/java/org/jboss/sbomer/core/features/sbom/Constants.java
core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/EnvironmentAttributesUtils.java
core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/commandline/CommandLineParserUtil.java
core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/commandline/gradle/GradleCommandLineParser.java
e2e/src/test/java/org/jboss/sbomer/test/e2e/E2EBase.java
e2e/src/test/java/org/jboss/sbomer/test/e2e/rw/StageGenerationRequestIT.java
e2e/src/test/resources/requests/A3LCEFCLLVYAA.json
e2e/src/test/resources/requests/A3YCIKLQTVYAA.json

Handle Gradle 4 and >=5 compatibilities; add e2e tests

Gradle enhancements

---

images/sbomer-generator/install.sh
images/sbomer-generator/install_cert.sh

This fixes image build problems we see after Oct 11th.

fix(images): update cert installation and java/maven versions

---

service/src/main/java/org/jboss/sbomer/service/feature/sbom/UserRoles.java

This reverts commit 6b186da9fbba944234d206fc3a755fdbcd4f10bc.

Revert "[NCL-8259] - Specify new roles for SBOMer"

---

.github/renovate.json

This is managed by Quarkus Operator SDK.

ci(renovate): disable updates for quarkus platform

---

pom.xml

https://issues.redhat.com/browse/NCL-8371
Supersedes https://github.com/project-ncl/sbomer/pull/338

chore: component upgrades: qosdk 6.6.0, quarkus: 3.7.0, josdk: 4.7.0

---

.github/actions/checkout/action.yml
service/src/main/resources/application.yaml

https://issues.redhat.com/browse/NCL-8378

fix(NCL-8378): do not validate unknown env vars

---

pom.xml

Supersedes https://github.com/project-ncl/sbomer/pull/355.

chore: upgrade: qosdk: 6.6.3, josdk: 4.8.0: quarkus: 3.7.2

---

pom.xml

This reverts commit 8aa5a520d60a1039876d8c1a4ba9467fb8e32049.

revert: chore: upgrade: qosdk: 6.6.3, josdk: 4.8.0: quarkus: 3.7.2

---

helm/templates/service/deployment.yaml
images/sbomer-service/run.sh
service/src/main/java/org/jboss/sbomer/service/feature/sbom/config/features/UmbConfig.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/AmqpUmbClientOptionProducer.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/AmqpMessageConsumer.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/PncBuildNotificationHandler.java
service/src/main/resources/application-prod.yaml
service/src/main/resources/application.yaml

We will do filtering on our end.

Receive all messages from UMB

---

helm/templates/service/deployment.yaml

https://issues.redhat.com/browse/SBOMER-3

feat(SBOMER-3): run two replicas of service deployment

---

images/sbomer-generator/runtime/func.sh
images/sbomer-generator/runtime/run.sh

This fixes a problem where SDKMAN! wasn't run at all (the tool selection didn't include anything to install), but we always wanted to initialize it.
Second is an enhancement and bugfix in one. When there are issues installing tools we will retry it up to 3 times. Better error handling was implemented as well.

Tool installation fixes

---

core/src/main/resources/META-INF/sbomer-config.yaml
docs/modules/user-guide/pages/configuration.adoc

@goldmann I remember there was a config installing multiple versions of domino, is it gone now? Thanks.

Upgrade to domino 0.0.103

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/client/SBOMerClient.java
cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/client/SBOMerClientTestIT.java
cli/src/test/resources/mappings/sbomer/sbom-123-search_v3.json
cli/src/test/resources/mappings/sbomer/sbom-123.json
cli/src/test/resources/mappings/sbomer/sbom-1234-not-found.json

This makes use of the latest fields available which were missing and causing generation failures.

fix: update to v1alpha3 for our client

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/CycloneDxGenerateOperationCommand.java
core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/SbomUtils.java

This PR will improve the content of ZIP manifesting, by listing all the binaries found inside the ZIP which matched the filters configured in the Deliverable Analyzer. Also, the dependency hierarchy is greatly improved to not have a simplistic flat list of dependencies, which does not reflect the structure of the ZIP.
The main components is now identified using the checksum, and relies on the new data available from orchestrator.
This PR fixes:
- https://issues.redhat.com/browse/SBOMER-62
- https://issues.redhat.com/browse/SBOMER-63

Modify the zip manifest generation to include pom components inside META-INF

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/service/PncService.java

https://issues.redhat.com/browse/SBOMER-74

fix: do not use token to contact PNC REST API

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/GradleCycloneDxGenerateCommand.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/MavenCycloneDxGenerateCommand.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/generate/MavenDominoGenerator.java
cli/src/test/java/org/jboss/sbomer/cli/test/unit/generate/MavenDominoGeneratorTest.java
images/sbomer-generator/runtime/run.sh
images/sbomer-service/run.sh

https://issues.redhat.com/browse/SBOMER-73

feat: adjust memory settings

---

images/sbomer-service/Containerfile
images/sbomer-service/run.sh

fix: the -XshowSettings:vm should be specified within JAVA_OPTIONS

---

.gitlab-ci.yml
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/ConfigReader.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/client/GitLabClient.java
cli/src/main/resources/application.yaml
cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/ConfigReaderIT.java

This adds support for retrieving config files from GitLab.

Support for GitLab

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

Reverts project-ncl/sbomer#445

Revert "chore(deps): update dependency maven-wrapper to v3.3.0"

---

docs/modules/user-guide/pages/api.adoc
service/src/main/resources/application-dev.yaml
service/src/main/resources/application-prod.yaml
service/src/main/resources/application-test.yaml
service/src/main/resources/application.yaml

@goldmann This is the first step to fix authentication issues

Enable CORS

---

core/src/main/resources/META-INF/sbomer-config.yaml
docs/modules/user-guide/pages/configuration.adoc

Upgrade domino to 0.0.107 to include fixes for issues pointed out by the Camel Quarkus team.

Upgrade to domino 0.0.107

---

pom.xml

Reverts project-ncl/sbomer#589

Revert "fix(deps): update dependency org.jboss.pnc.build.finder:core to v2.4.2"

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/adjuster/SyftImageAdjuster.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/process/DefaultProcessorProducer.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/processor/DefaultProcessor.java
cli/src/test/java/org/jboss/sbomer/cli/test/integ/DefaultProcessCommandIT.java
cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/processor/DefaultProcessorIT.java
cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/DefaultProcessorTest.java
cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/adjust/SyftImageAdjusterTest.java
cli/src/test/java/org/jboss/sbomer/cli/test/utils/KojiServiceAlternative.java
cli/src/test/java/org/jboss/sbomer/cli/test/utils/KojiSessionAlternative.java
cli/src/test/resources/boms/image-after-adjustments.json
core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/SbomUtils.java
e2e/src/test/java/org/jboss/sbomer/test/e2e/E2EBase.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/generator/image/syft/controller/SyftImageController.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/producer/NotificationService.java

This does not make any functional changes, but adds some logging and changes the way we prcoess things internally. End result should be the same, but it should help overcome an issue on stage.

refactor: stabilization and logging

---

e2e/pom.xml

This pom gives an error for me, and I must be using the same Maven version (since I tried with `mvnw`). But I wasn't sure what was intended here.

Set e2e packaging to pom

---

core/src/test/java/org/jboss/sbomer/core/test/unit/SbomUtilsTest.java

Works for me in Temurin JDK (OpenJDK Runtime Environment Temurin-17.0.12+7 (build 17.0.12+7)). Retry?

Reenable SBOM utils test

---

core/src/test/java/org/jboss/sbomer/core/test/unit/SbomUtilsTest.java

This reverts commit 7e946ea40f550dcd9461af3520b6afafb8503b3b.
Still fails on CI.

revert: "Reenable SBOM utils test"

---

images/sbomer-generator/install.sh
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/generator/AbstractController.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/generator/image/syft/controller/SyftImageController.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/SbomRepository.java
service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/BuildControllerTest.java
service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/syftimage/SyftImageControllerTest.java

Additionally upgrades syft from 1.8.0 to 1.12.2.
Fixes SBOMER-145

feat(SBOMER-145): add support for multi-arch container images

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/adjuster/SyftImageAdjuster.java
cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/adjust/SyftImageAdjusterTest.java
core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/SbomUtils.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/generator/AbstractController.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/generator/image/syft/controller/SyftImageController.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/BuildController.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/OperationController.java
service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/BuildControllerTest.java
service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/atlas/AtlasHandlerTest.java
service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/syftimage/SyftImageControllerTest.java

Moves the post actions to be executed as part of the `reconcileGenerating` method.
Adjusted tests.

Reconcile logic updates

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/adjuster/Adjuster.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/adjuster/PncBuildAdjuster.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/adjuster/SyftImageAdjuster.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/adjust/AbstractAdjustCommand.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/adjust/SyftImageAdjustCommand.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/processor/DefaultProcessor.java
cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/adjust/PncBuildAdjusterTest.java
cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/adjust/SyftImageAdjusterTest.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/atlas/AtlasHandler.java
service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/atlas/AtlasHandlerTest.java

Fixes: https://issues.redhat.com/browse/SBOMER-157

fix(SBOMER-157): set serialNumber, if missing

---

docs/modules/admin-guide/pages/features.adoc
service/src/main/java/org/jboss/sbomer/service/feature/sbom/config/features/UmbConfig.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/AmqpMessageConsumer.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/producer/NotificationService.java
service/src/main/resources/application-dev.yaml
service/src/main/resources/application-prod.yaml
service/src/main/resources/application-test.yaml
service/src/main/resources/application.yaml
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/s3/S3FeatureIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/s3/S3StorageHandlerTestIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/SBOMResourceRSQIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/SBOMServiceTestIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/SbomGenerationRequestRepositoryIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/SbomRepositoryIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/generation/SyftImageResourceIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/k8s/reconciler/GenerationPhaseGenerationRequestReconcilerIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/k8s/reconciler/InitializationPhaseGenerationRequestReconcilerIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/messaging/AmqpMessageConsumerIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/messaging/GenerationFinishedMessageBodyIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/messaging/PncBuildIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/rest/ErrorResourcesIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/rest/SBOMResourceIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/rest/StatsResourceIT.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/umb/producer/NotificationServiceIT.java
service/src/test/java/org/jboss/sbomer/service/test/utils/umb/AmqpTestResourceLifecycleManager.java
service/src/test/java/org/jboss/sbomer/service/test/utils/umb/TestAmqpUmbClientOptionProducer.java
service/src/test/java/org/jboss/sbomer/service/test/utils/umb/TestUmbProfile.java
ui/.editorconfig

This is moving around configuration and created base work for ET listener.

Refactoring to add support for Errata listener

---

service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/generator/image/syft/controller/SyftImageController.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/producer/NotificationService.java
service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/umb/producer/NotificationServiceIT.java

Should not fail for non-product manifests.

Fix for sending umb messages

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/adjuster/SyftImageAdjuster.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/processor/DefaultProcessor.java
cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/DefaultProcessorTest.java
cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/adjust/SyftImageAdjusterTest.java
cli/src/test/resources/boms/image-after-adjustments.json

The main component representing the image should be located in the root components list (probably first one). It should contain all properties, build information, etc.
The metadata component should be a bare representation of the main component containing product release metadata, in case it is a release manifest.

Container image metadata component cleanup

---

core/src/main/java/org/jboss/sbomer/core/features/sbom/config/Config.java
core/src/test/java/org/jboss/sbomer/core/test/unit/config/ConfigTest.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/resources/TaskRunInitDependentResource.java

Remove whitespace before proceeding with config reading.

fix: default value changed to empty string

---

core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/commandline/maven/MavenCommandLineParser.java
core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/commandline/maven/MavenCommandOptions.java
core/src/test/java/org/jboss/sbomer/core/test/unit/MavenCommandLineParserTest.java

[SBOMER-228] - Handle alternative pom file location in maven command parser

---

pom.xml

Reverts project-ncl/sbomer#921

Revert "chore(deps): update dependency org.sonarsource.scanner.maven:sonar-maven-plugin to v5"

---

images/sbomer-generator/install.sh

Reverts project-ncl/sbomer#965
Sorry!

Revert "Revert "feat: upgrade syft to 1.16.0""

---

.gitlab-ci.yml

This takes the generation of documentation from 7 min to 2.

ci: improve speed of documentation building

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/CycloneDxGenerateOperationCommand.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/processor/DefaultProcessor.java
cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/DefaultProcessorTest.java
cli/src/test/resources/boms/operation.json
core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/SbomUtils.java

This will enhance all components in manifests generated from deliverables.

feat(SBOMER-142): Enhance handling of bundled JavaScript content

---

hack/generate-release-notes.sh

Generates stub for releases notes for last 5 deployments.

chore: update release notes generator

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/adjuster/SyftImageAdjuster.java

This code had a few errors. The `name` could be `null` when `split()` was called.
It was using a combination of `substring()` and `split()`, when just one would do and it looks like the substring was off by one.
Unfortunately, we still don't have a test for a `null` name label, so we probably won't hit that code in practice.

fix: Fix component name

---

e2e/src/test/java/org/jboss/sbomer/test/e2e/rw/AdvisoryGenerationRequestIT.java

https://issues.redhat.com/browse/SBOMER-340

test(advisory): enable rpm test, disable container image test

---

images/sbomer-generator/cyclonedx-init.gradle

Reverts project-ncl/sbomer#1137

Revert "fix(SBOMER-337): Allow insecure protocols in Gradle for our cache"

---

ui/src/app/components/ManifestsTableTable/ManifestsTable.tsx
ui/src/app/components/RequestEventTable/RequestEventTable.tsx

User features added:
- Search on Enter Key press for searchbar in Manifests and Request Events page

feat(ui): added search for filters on Enter key press

---

ui/src/app/components/Pages/GenerationRequests/GenerationRequestPageContent.tsx

Features:
- While request has status "In progress", info message is displayed instead of error saying that logs are irretrievable.

fix(SBOMER-215): improve handling logs in progress status

---

ui/src/app/components/GenerationRequestTable/GenerationRequestTable.tsx
ui/src/app/components/ManifestsTableTable/ManifestsTable.tsx
ui/src/app/components/RequestEventTable/RequestEventTable.tsx

Separated filter bar from table data for Manifests and Requests page. Changed code structure for Generations page to be the same as for other pages.

feat(ui): optimize structure of all tables in the UI

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/processor/WorkaroundMissingNpmDependencies.java
cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/WorkaroundMissingNpmDependenciesTest.java

Fix NPE when enhancing manifest with no components

---

images/sbomer-service/run.sh

Lower InitialRAMPercentage to 20% and MaxRAMPercentage to 50%. Enable NativeMemoryTracking=summary to better understand memory issues.

Update JVM params for the service

---

service/src/main/java/org/jboss/sbomer/service/feature/sbom/atlas/AtlasClient.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/errata/ErrataClient.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/pyxis/PyxisClient.java
service/src/main/java/org/jboss/sbomer/service/pnc/PncClient.java
service/src/main/java/org/jboss/sbomer/service/rest/faulttolerance/Constants.java

https://issues.redhat.com/browse/SBOMER-249

SBOMER-249 Use retries for Atlas upload in case of failures

---

pom.xml

Reverts project-ncl/sbomer#1248

Revert "fix(deps): update dependency io.quarkiverse.unleash:quarkus-unleash to v1.10.0"

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/SbtCycloneDxGenerateCommand.java
cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/processor/DefaultProcessor.java
cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/DefaultProcessorTest.java
core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/SbomUtils.java

https://issues.redhat.com/browse/SBOMER-418

SBOMER-418 Invalid Reference when uploading to Atlas v2

---

service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/generator/rpm/controller/BrewRPMController.java
service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/BrewRPMControllerTest.java

* Added specific check for exit code 10
* Change GenerationResult to generation error rather than system error

feat(SBOMER-409): be more verbose about failed brew RPM taskrun

---

service/src/main/java/org/jboss/sbomer/service/nextgen/service/model/BaseStatusHistory.java
service/src/main/java/org/jboss/sbomer/service/nextgen/service/model/Event.java
service/src/main/java/org/jboss/sbomer/service/nextgen/service/model/Generation.java
service/src/main/java/org/jboss/sbomer/service/nextgen/service/model/Manifest.java

In case we will share the ID it will be come clear what is the ID about.

feat: prefix entity ID's to make it clear what these are

---

cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/processor/WorkaroundMissingNpmDependencies.java

The original data structures are lists, but converting to hash sets could lose the original order.

fix: Preserve the original order of lists in BOM for reproducibility

---

service/src/main/java/org/jboss/sbomer/service/feature/sbom/errors/ClientExceptionMapper.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/runtime/LoggingFilter.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/LoggingService.java

https://issues.redhat.com/browse/SBOMER-395

SBOMER-395 Some traces are not available in SignalFX

---

cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/adjust/SyftImageAdjusterTest.java
cli/src/test/resources/boms/go-image.json
cli/src/test/resources/boms/image.json
service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/RequestEventRepository.java

https://issues.redhat.com/browse/SBOMER-431

SBOMER-431 Fix failing test in SyftImageAdjusterTest

---

service/src/main/resources/application.yaml

To resolve 503 errors mentioned in SBOMER-469

Increase db connections timeouts, lower concurrent generations

---

service/src/main/java/org/jboss/sbomer/service/feature/sbom/errors/ClientExceptionMapper.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/runtime/LoggingFilter.java
service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/LoggingService.java
service/src/main/resources/application-prod.yaml

https://issues.redhat.com/browse/SBOMER-395

SBOMER-395 Use build time property to fix tracing
