- k8s/overlays/staging/kustomization.yaml
Rely on the trustore configured internally inside a mounted volume, use the keystore from the secret.
> Use the trustore configuration from the mounted certificates volume

- cli/src/main/java/org/jboss/sbomer/cli/commands/processor/RedHatProductProcessCommand.java
- cli/src/test/java/org/jboss/sbomer/cli/test/command/processor/RedHatProductProcessCommandTest.java
- core/src/main/java/org/jboss/sbomer/core/utils/Constants.java
- k8s/overlays/production/kustomization.yaml
- k8s/overlays/production/patches/route.yaml
- k8s/overlays/production/patches/service.yaml
- k8s/overlays/staging/kustomization.yaml
- k8s/overlays/staging/service/route.yaml
- service/src/main/java/org/jboss/sbomer/features/umb/UmbConfig.java
- service/src/main/java/org/jboss/sbomer/features/umb/producer/MessageProducer.java
- service/src/main/java/org/jboss/sbomer/features/umb/producer/NotificationService.java
- service/src/main/java/org/jboss/sbomer/features/umb/producer/UmbMessageProducer.java
- service/src/main/java/org/jboss/sbomer/service/NotificationService.java
- service/src/main/java/org/jboss/sbomer/service/ProcessingService.java
- service/src/main/resources/application.yaml
- Move errata product names properties to the other constants
- Add retries configuration properties for the Umb producer
- Implement the UMB sender
- Implement a Notification service to send sbom creation events via UMB
- Expose the public route to be used when sending notification UMB messages
> [NCL-7695] - Setup UMB sender

- cli/src/main/java/org/jboss/sbomer/cli/client/SBOMerClient.java
- cli/src/main/java/org/jboss/sbomer/cli/commands/generator/AbstractMavenGenerateCommand.java
- service/src/main/java/org/jboss/sbomer/features/umb/consumer/PncMessageParser.java
- service/src/main/java/org/jboss/sbomer/rest/v1alpha1/SBOMResource.java
- service/src/main/resources/application.yaml
- service/src/test/java/org/jboss/sbomer/test/messaging/GenerationFinishedMessageBodyTest.java
- service/src/test/java/org/jboss/sbomer/test/messaging/PncBuildTest.java
The idea behind this is to be able to handle builds which have status BUILD_NOT_REQUIRED. Such builds need to handle differently the way they retrieve the scmUrl and scmTag. Also, in case the original builds has been already generated, we can reuse the same original SBOM instead of regenerating it again (which would give the same result because the code ha not changed). It is correct to process again the SBOM with enrichments, because in the meantime more builds could be available and provide more metadata for the enrichments.
The uncommented endpoint will get some query API in the future, so to reduce the number of endpoints to re-expose.
> Handle builds with status BUILD_NOT_REQUIRED

- k8s/overlays/production/kustomization.yaml
- k8s/overlays/production/patches/tekton/cm.yaml
This includes the changes to use the correct secrets and keystore in Production environment.
Once we will work on the deployment jobs, we will also update the images to reference existing tags inside the production image registry (instead of the latest tag in the staging image repository)
> Adjust k8 resources for the production environment

- images/sbomer-service/run.sh
- k8s/overlays/production/kustomization.yaml
- k8s/overlays/staging/kustomization.yaml
I updated secrets names in Hashicorp Vault & added env vars to match new naming. Added secret-name annotation to `kustomization.yaml` as well.
> Add annotations to resolve secret name env var

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/GenerationRequest.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/GenerationRequestReconciler.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/resources/Labels.java
- service/src/test/java/org/jboss/sbomer/service/test/feature/sbom/k8s/reconciler/InitializationPhaseGenerationRequestReconcilerTest.java
This fixes the sbomer.jboss.org/phase setting on the GenerationRequest as well adds new label sbomer.jboss.org/phase.
Previously the status was set to phase, but in order to unify labels with depednent resources this was adjusted to align with them.
And more tests!
> feat: add more tests and label adjustments on generation request

- cli/src/test/java/org/jboss/sbomer/cli/test/feature/sbom/command/CycloneDXPluginMavenGenerateCommandTest.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/config/SbomConfig.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/GenerationRequestReconciler.java
- service/src/main/resources/application.yaml
- service/src/test/java/org/jboss/sbomer/service/test/feature/sbom/k8s/reconciler/GenerationPhaseGenerationRequestReconcilerTest.java
Cleanup is controlled in application (service) settings. When enabled the Kubernetes resource as well as all dependent resources are removed from the cluster. Additionally any leftovers on the volume are cleaned too.
Removal is done no matter if the status is FINISED or FAILED. Resources are synced with the DB earlier, plus we have logs available in a separate system so we can debug everything at any time.
https://issues.redhat.com/browse/NCL-7964
> feat: support for cleaning up resources when generation is finished

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/MavenDominoGenerateCommand.java
- docs/usage.md
This subcommand has been deprecated a long time ago. Domino figures out whether it's pointed at a Maven or Gradle project and proceeds with the dependency analysis accordingly.
> Remove 'from-maven' domino subcommand

- cli/pom.xml
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/MavenDominoGenerateCommand.java
- cli/src/test/java/org/jboss/sbomer/cli/test/feature/sbom/generate/MavenDominoGeneratorTest.java
- pom.xml
Additionally remove the logcaptor dependency for now, because it is impossible to run the tests in Maven and vscode due to the multiple SLF4J providers issue.
> fix(cli): pass the path to settings.xml file

- e2e/pom.xml
- e2e/src/test/java/org/jboss/sbomer/test/e2e/E2EBase.java
- e2e/src/test/java/org/jboss/sbomer/test/e2e/E2EStageBase.java
- e2e/src/test/java/org/jboss/sbomer/test/e2e/rw/StageGenerationRequestIT.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/producer/NotificationService.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/producer/UmbMessageProducer.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/producer/model/Sbom.java
- service/src/main/resources/schemas/message-success-schema.json
This adds `generation_request_id` header to the UMB complete message notification, as well as to the body:
```json
"sbom": {
"generationRequest": {
"id": "AABBCC"
}
}
```
> feat(umb): add generation request information to messages

- cli/pom.xml
- pom.xml
- service/pom.xml
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/model/Sbom.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/model/SbomGenerationRequest.java
We refrain from defining the Quarkus version explicitly now. Instead we use the transient version as defined by the Operator SDK Quarkus extension. This means that we are now at Quarkus 3.2.4.Final.
Unification of naming of properties related to versions was done as well.
Removal of custom Hibernate types. It's not needed anymore in Quarkus 3 which uses Hibernate 6.2.
> chore: version unification

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/auto/GenerateConfigCommand.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/service/PncService.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/service/pnc/GroupConfigurationClient.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/service/pnc/GroupConfigurationEndpoint.java
- cli/src/main/resources/mapping/prod/product-mapping.yaml
- cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/service/PncServiceIT.java
- cli/src/test/resources/mappings/build-BUILDWITHGROUPSCONFIGPRODUCT.json
- cli/src/test/resources/mappings/build-config-666.json
- cli/src/test/resources/mappings/group-config-666.json
- core/src/main/java/org/jboss/sbomer/core/features/sbom/config/runtime/Config.java
In case the build config used to build the project doesn't have the `productVersion` set, we will try to get this information from a group configuration this build config is assigned to (if any).
In case the build config is assigned to multiple group configs -- we will take into account all of them. This will result in multiple "products" in SBOMer terms which will rpoduce multiple SBOMs for all of the productVersions found.
> feat: add support for retrieving product version from group config

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/GradleCycloneDxGenerateCommand.java
- images/sbomer-generator/cyclonedx-init.gradle
@goldmann Ok, here I make the plugin version configurable via config options. I might in future add some logic to override the version based on the Gradle version required, as it looks like older Gradle versions (4.10) does not work with versions 1.7.x of the plugin. But with this PR, it will be possible to specify the version via configuration.
> Make the gradle cyclonedx plugin version configurable with config options

- e2e/src/test/java/org/jboss/sbomer/test/e2e/rw/StageGenerationRequestIT.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/PncMessageParser.java
This adds handling for errors that are thrown by the system. In case of a failure, it is logged (as error, with the exception as well) and the flag of being connected is set to false. I was thinking whether this is the best approach or not.
I don't think the proposed logic is perfect. It forces reconnection on any JMS exception, but I haven't figured out (yet) more accurate representation of fatal errors.
> fix(service): handle more UMB errors and force the reconnection

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/service/PncService.java
- docs/development.md
- helm/templates/tekton/task-env-config.yaml
- helm/templates/tekton/task-generate.yaml
- helm/templates/tekton/task-init.yaml
This makes the OIDC client disabled for dev mode.
Additionally upgrade Tekton to be in sync with OpenShift.
> fix(oidc): ensure dev mode works after introducing oidc client

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/rest/QueryParameters.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/rest/v1alpha2/SBOMResource.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/SbomService.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/SBOMResourceRSQIT.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/SBOMServiceTestIT.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/SbomRepositoryIT.java
This new endpoint makes it possible to retrieve the SBOM by giving just the purl. In case of multiple SBOMs will be found for a given purl, latest SBOM will be returned.
In case no SBOM can be found, 404 will be returned.
Additionally `/sboms/purl/[PURL]/bom` is exposed as well to retrieve the BOM content.
> feat(service): NCL-8201: exposure of /sboms/purl/[PURL] endpoint

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/service/PncService.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/utils/auth/TokensAlternative.java
- cli/src/main/resources/application.yaml
Fixes according to: https://quarkus.io/guides/all-config#quarkus-oidc-client_quarkus.oidc-client.client-enabled
> fix(oidc): use proper configuration properties for the OIDC client

- core/src/main/resources/META-INF/sbomer-config.yaml
- core/src/test/java/org/jboss/sbomer/core/test/unit/config/SbomerConfigProviderTest.java
- images/sbomer-generator/install.sh
* record dependency graphs instead of trees (in line with the CycloneDX Maven plugin)
* use CycloneDX spec 1.5
`--include-non-managed` is enabled by default when `--manifest` is present.
> Upgrade to domino 0.0.100

- pom.xml
This update will solve the issue of Build Finder not finding the signed artifacts in Brew, updating to the latest released version. Build Finder PR is https://github.com/project-ncl/build-finder/pull/886
> Update the Build Finder version to 2.3.0

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/SbomService.java
When returning generation requests pages, do the paging correctly. Currently it fails because we try to  count Sbom entities instead of SbomGenerationRequests.
> fix(api): page generation requests properly

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/PncMessageParser.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/UmbMessageConsumer.java
Add periodic reconnects in case no new messages were received over particular period of time. Currently it is configured for allowing up to 3 hours of quiet period. If more than this is discovered, a client reconnection is scheduled.
> feat(NCL-8317): add periodic reconnects

- helm/templates/service/deployment.yaml
- service/pom.xml
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/config/features/UmbConfig.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/AmqpUmbClientOptionProducer.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/AmqpMessageConsumer.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/PncBuildNotificationHandler.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/PncMessageParser.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/UmbMessageConsumer.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/producer/AmqpMessageProducer.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/producer/NotificationService.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/producer/UmbMessageProducer.java
- service/src/main/resources/application-prod.yaml
- service/src/main/resources/application.yaml
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/messaging/PncBuildIT.java
https://issues.redhat.com/browse/NCL-8323
This is an attempt to implement support for sending UMB messages using the SmallRye Reactive Messaging framework. It looks like its much more elegant to use and I hope it will be more stable as well. Switching from Qpid makes handling of receiving and sending messages much easier.
This is added in addition to the already existing Qpid support. I hope to test this on stage and eventually remove qpid support entirely.
> Support for SmallRye Reactive messaging

- e2e/src/test/java/org/jboss/sbomer/test/e2e/rw/StageGenerationRequestIT.java
- e2e/src/test/resources/junit-platform.properties
- e2e/src/test/resources/logging.properties
Small caveat is that the logs are now mixed, like this:
```
14:48:49,534 INFO  [StageGenerationRequestIT] Gradle 5 build - Current generation request status: ENV_DETECTING
14:48:49,535 INFO  [StageGenerationRequestIT] Maven build - Current generation request status: INITIALIZING
14:48:49,537 INFO  [StageGenerationRequestIT] Gradle 4 build - Current generation request status: ENV_DETECTING
14:48:55,052 INFO  [StageGenerationRequestIT] Gradle 5 build - Current generation request status: ENV_DETECTING
14:48:55,060 INFO  [StageGenerationRequestIT] Maven build - Current generation request status: INITIALIZING
14:48:55,063 INFO  [StageGenerationRequestIT] Gradle 4 build - Current generation request status: ENV_DETECTING
14:49:00,568 INFO  [StageGenerationRequestIT] Maven build - Current …
```
> test: make e2e tests run concurrently

- antora-playbook-dev.yml
- antora-playbook.yml
- docs/antora.yml
This ensures a better URL after publishing to GitLab pages.
> docs: rename the main module from sbomer to antora

- helm/templates/service/deployment.yaml
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/SbomerLeaderElectionConfigurationProducer.java
As part of the SBOMer HA effort, this ensures that we can run multiple replicas of our deployments. This is to spread the load and decrease the probability of failure **in the same cluster**.
This is not about multi-cluster support.
https://issues.redhat.com/browse/SBOMER-3
> Support running multiple replicas of service in a deployment

- cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/client/SBOMerClientTestIT.java
- core/src/main/java/org/jboss/sbomer/core/dto/v1alpha2/SbomRecord.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/SBOMResourceIT.java
This fixes the case where there is a difference in the respose between v1alpha1 and v1alpha2 API. The /sboms endpoint returned elements with `sbomGenerationRequest` field, but it should be `generationRequest` instead.
> feat(SBOMER-45): record should match what is in the entity

- .gitlab-ci.yml
- pom.xml
- service/pom.xml
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/FeatureFlags.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/producer/NotificationService.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/rest/v1alpha1/SBOMResource.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/rest/v1alpha2/SBOMResource.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/rest/v1alpha3/SBOMResource.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/runtime/ApplicationLifecycle.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/SbomService.java
- service/src/main/resources/application.yaml
- service/src/main/resources/db-update/00010-1.0.2.sql
Initial implementation adds support for a single `dry-run` toggle. When enabled, no changes will be allowed to be made via the REST API returning 405 HTTP code.
Support for disabling UMB processing will be added later, because it is non-trivial to disable/enable it on demand.
In dev mode, feature flags are disabled entirely and default values from `FeatureFlags` class will be used.
> feat: add support for feature-flags

- cli/src/main/resources/mapping/prod/product-mapping.yaml
- core/src/main/resources/META-INF/sbomer-config.yaml
- core/src/test/java/org/jboss/sbomer/core/test/unit/config/SbomerConfigProviderTest.java
Default SCM locator used by Domino is slow and has problems when deployed in a constrined environment not allowing to connect to not-whitelisted hosts.
https://issues.redhat.com/browse/SBOMER-76
> fix(SBOMER-76): use --legacy-scm-locator by default when using Domino generator

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/PncNotificationHandler.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/GenerationRequestBuilder.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/GenerationRequestFluent.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/SbomService.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/k8s/reconciler/GenerationPhaseGenerationRequestReconcilerIT.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/k8s/reconciler/GenerationRequestReconcilerIT.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/k8s/reconciler/InitializationPhaseGenerationRequestReconcilerIT.java
Previously the generation request name was based
on the build identifier. This was a bit problematic when we wanted to gather all logs related to it.
Basing it on the `id` makes it much easier.
https://issues.redhat.com/browse/SBOMER-70
> feat: sbom generation request names contain id

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/service/PncService.java
- core/src/main/java/org/jboss/sbomer/core/config/DeliverableAnalysisConfigSchemaValidator.java
- core/src/main/java/org/jboss/sbomer/core/features/sbom/config/runtime/DeliverableAnalysisConfig.java
- core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/commandline/CommandLineParserUtil.java
- core/src/main/resources/schemas/deliverable_analysis_config.json
- core/src/test/java/org/jboss/sbomer/core/test/unit/config/DeliverableAnalysisConfigSchemaValidatorTest.java
- docs/modules/user-guide/pages/api.adoc
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/config/PncConfig.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/PncNotificationHandler.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/SbomGenerationStatus.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/GenerationRequestReconciler.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/model/SbomGenerationRequest.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/rest/v1alpha3/SBOMResource.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/PncClientsWrapper.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/SbomService.java
- service/src/main/resources/application-dev.yaml
- service/src/main/resources/application-prod.yaml
- service/src/main/resources/application-test.yaml
This replaces https://github.com/project-ncl/sbomer/pull/471.
@goldmann This PR is meant to expose a new REST API to trigger a new Deliverable Analysis operation in PNC.
- The REST API will create an entry in the DB containing the Product Config metadata and the identifier of the new operation created in PNC via the PncService. It will not create any ConfigMap because there would be nothing to do anyway, as the creation of the new analysis in PNC will send back a UMB notification once finished. Until then, there is nothing to do
- Once a UMB notification is received, if there is a pending requests in the DB which a matching operation Id, it will be used to create a new ConfigMap with the same id, otherwise a new ConfigMap will be created.
> [SBOMER-29] - Expose API endpoint to request SBOM generation for output from DelAnalyzer

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/processor/DefaultProcessor.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/service/PncService.java
In case the artifact does not have a purl set, don't fail and use the old purl. Log a warning as well.
> fix: handle lack of purl in artifacts

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/generator/AbstractController.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/producer/NotificationService.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/BuildController.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/SbomRepository.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/SbomRepositoryIT.java
This PR contains fixes for two things:
1. UMB notifications are send only after manifests are persisted in the database which makes it possible to handle case where failure in sending messages could prevent from updating the generation status
2. Storing in S3 is enabled for failed generations as well.
https://issues.redhat.com/browse/SBOMER-102
https://issues.redhat.com/browse/SBOMER-99
> UMB and S3 fixes

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/adjuster/SyftImageAdjuster.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/adjust/SyftImageAdjustCommand.java
- cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/adjust/SyftImageAdjusterTest.java
- cli/src/test/resources/boms/image.json
- core/src/main/java/org/jboss/sbomer/core/features/sbom/config/SyftImageConfig.java
- core/src/main/resources/schemas/syft-image-config.json
- docs/modules/user-guide/pages/configurations/syft-image.adoc
Adds support for adding RPM components to the manifest. If the rpms flag is set to true, RPMs will be preserved in the manifest. Otherwise (the default option) RPM components will be removed.
https://issues.redhat.com/browse/SBOMER-91
> feat(SBOMER-91): add RPM content support for container images

- cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/client/ServiceWireMock.java
- cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/processor/DefaultProcessorIT.java
- cli/src/test/java/org/jboss/sbomer/cli/test/utils/PncWireMock.java
- service/src/test/java/org/jboss/sbomer/service/test/PncWireMock.java
Do we need fixed ports? I keep getting errors that the port is already in use.
> Use dynamic port for WireMock server

- cli/src/test/java/org/jboss/sbomer/cli/test/integ/CliIT.java
Comparing as string rather than list so that whitespace in the line isn't a factor.
> Change test so that it ignores whitespace

- core/pom.xml
- pom.xml
Three changes:
1. `maven.compiler.*` shouldn't be needed, but fixes import into IDEA apparently
2. Set `LF` explicitly for the formatter
3. jandex-maven-plugin seems to be an old version and this version seems to work with newer JDKs
> Fix some issues with the Maven build

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/PathConverter.java
- cli/src/test/java/org/jboss/sbomer/cli/test/unit/cli/PathConverterTest.java
So, this didn't work as expected. I am not really sure of the use case, but this is what I found:
1. It replaced the _first occurrence_ of `~` which is not necessarily the first character.
2. Using `System.getProperty("user.home")` is cross-platform while `System.getenv("HOME")` isn't, and I guess technically these could return `null`.
3. Removed the use of a regex. Could have tried to replace `~` with `^~`, but the regex does not handle "special" characters in paths.
> Fix path converter

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/provider/BuildFinderConfigProvider.java
This seems to indicate that 0700 is already the default https://nvd.nist.gov/vuln/detail/CVE-2020-8908/change-record?changeRecordedOn=02/16/2021T18:15:13.103-0500 but I wouldn't believe it without checking the code.
In any case, only set POSIX perms if supported.
> Only set POSIX file permissions if supported

- cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/ConfigReaderIT.java
- core/src/test/java/org/jboss/sbomer/core/test/unit/config/SbomerConfigProviderTest.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/s3/S3FeatureIT.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/SbomRepositoryIT.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/messaging/PncBuildIT.java
- service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/BuildControllerTest.java
- service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/syftimage/TaskRunSyftImageGenerateDependentResourceTest.java
* Replace mix of junit4/junit5 classes with junit5
* Simplify `assertTrue`/`instanceOf` calls by using `assertInstanceOf`
> Fix some JUnit API issues

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/processor/DefaultProcessor.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/service/KojiService.java
- cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/processor/DefaultProcessorIT.java
- cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/DefaultProcessorTest.java
- core/src/main/java/org/jboss/sbomer/core/pnc/PncService.java
In case the main component is a container image we will try to add more information. First we will try to see whether it was built in Brew. If it was, we will query Brew and populate following fields:
* supplier
* publisher
* build system external resource
* vcs external resource
* and finally a pedigree commit.
https://issues.redhat.com/browse/SBOMER-121
> feat(SBOMER-121): additional metadata for container images

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/CycloneDxGenerateOperationCommand.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/OperationController.java
This is a workaround for https://issues.redhat.com/browse/SBOMER-126.
> feat(SBOMER-126): handle case where distribution does not provide hash

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/adjuster/SyftImageAdjuster.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/adjust/SyftImageAdjustCommand.java
- core/src/main/java/org/jboss/sbomer/core/features/sbom/config/SyftImageConfig.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/generator/image/syft/controller/TaskRunSyftImageGenerateDependentResource.java
- service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/syftimage/TaskRunSyftImageGenerateDependentResourceTest.java
The `rpms` parameter from configuration was not passed and thus ignored. The default value of `false` was used meaning that RPMs were not added to the manifest.
Fixes: https://issues.redhat.com/browse/SBOMER-128
> feat(SBOMER-128): pass rpms parameter to the task run

- service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/syftimage/SyftImageControllerTest.java
* Use Junit 5 classes
* Sort paths as the visit order is non-deterministic
> fix: make `findSomeManifests` test deterministic

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/adjuster/SyftImageAdjuster.java
- cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/adjust/SyftImageAdjusterTest.java
All qualifiers besides 'arch' and 'epoch' are removed from purl for RPM components in the syft cntainer image generator.
Fixes: https://issues.redhat.com/browse/SBOMER-149
> feat(SBOMER-149): clean up RPM purls in syft iamge adjuster

- e2e/src/test/resources/requests/A3LCEFCLLVYAA.json
The problem is that the main component (metadata/component) does not have the build information attached, because the artifact cannot be found in PNC and thus the information about the build system wasn't added to external references in the main component.
This comimt stops setting the product coordinates for this specific e2e, but this is just a workaround. The proper fix will be implemented later.
Related: https://issues.redhat.com/browse/SBOMER-26
Fixes: https://issues.redhat.com/browse/SBOMER-166
> fix(SBOMER-166): do not set product coordinates to not send UMB message

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/AmqpMessageConsumer.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/PncNotificationHandler.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/SbomService.java
Because we only ACK the message when we successfully create a `GenerationRequest` CR and sync it with the DB we probably can use this fact to check whether a `SbomGenerationRequest` entity already exists for a given PNC build.
I think it is safe to assume that if it exists, it was created by processing another message. It could help with processing duplicate UMB messages, because we have a single active consumer and we process next message only when we ACK or reject previous message.
https://issues.redhat.com/browse/SBOMER-167
WDYT @vibe13?
> fix(SBOMER-167): do not create new requests if we already handle it

- core/src/main/java/org/jboss/sbomer/core/config/SbomerConfigProvider.java
- core/src/main/java/org/jboss/sbomer/core/features/sbom/config/Config.java
- core/src/main/resources/schemas/operation_config.json
- core/src/test/java/org/jboss/sbomer/core/test/unit/config/ConfigTest.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/model/GenerationRequest.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/resources/TaskRunOperationInitDependentResource.java
This PR fixes some inconsistencies in operation handling. Operation schema was updated, because it was wrong according to what we generate internally. Now it is allowed to not provide product config. Handling of empty config was fixed as well.
> fix(SBOMER-171):  bugfixing operation handling

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/adjuster/SyftImageAdjuster.java
Fixes exception:
```
Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because the return value of "org.cyclonedx.model.Bom.getComponents()" is null
```
> Check for null components when adjusting BOM

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/k8s/reconciler/TektonResourceUtils.java
- service/src/main/java/org/jboss/sbomer/service/generator/image/controller/TaskRunSyftImageGenerateDependentResource.java
- service/src/main/resources/application.yaml
- service/src/test/java/org/jboss/sbomer/service/test/unit/feature/sbom/reconciler/TektonResourceUtilsTest.java
It does this based on the configuration and it can be overridden by an env variable.
Currently covering only container image generations, will be extended to other types if it proves to be working properly.
> feat(SBOMER-224): adjust syft image TaskRun compute resources

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/AmqpMessageConsumer.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/ErrataNotificationHandler.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/PncNotificationHandler.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/model/SbomGenerationRequest.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/AdvisoryService.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/messaging/PncBuildIT.java
This replaces https://github.com/project-ncl/sbomer/pull/905
@goldmann The Transactional annotation was introduced to force the initialization of the AmqpMessageConsumer after the DB connection initialization. However, this has introduced as a side effect a timeout constraint of 60 seconds on the "processErrata" and "process" methods. For big advisories, more time will be definitely needed to complete the bootstrapping of all the generations. I would remove the annotations from the class altogether. Since we have now a readiness probe for the DB pool initialization, we should be ok.
I have used TxType.REQUIRES_NEW so to make sure that the RequestEvents are updated all the times, even if an outre transaction fails. This is to ensure we keep the audit of events on track.
> feat: remove transactional annotations from UMB consumer

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/GradleCycloneDxGenerateCommand.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/MavenCycloneDxGenerateCommand.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/generate/MavenDominoGenerator.java
- cli/src/test/java/org/jboss/sbomer/cli/test/unit/generate/MavenDominoGeneratorTest.java
- images/sbomer-generator/runtime/run.sh
These settings control only the SBOMer CLI that launches the generator. Generator itself has own set of resource limits.
Bump memory settings for Domino and CycloneDX plugins.
> fix: make the JVM settings for generator static

- service/src/main/resources/application.yaml
Different subscription IDs should make clients receive messages in parallel.
> fix(SBOMER-244): use different subscription IDs across AZ to handle load in parallel

- core/src/main/resources/META-INF/sbomer-config.yaml
- docs/modules/user-guide/pages/generation/configuration/pnc-build.adoc
- docs/modules/user-guide/pages/generation/generators/maven-domino.adoc
- service/src/main/java/org/jboss/sbomer/service/rest/api/v1beta1/GenerationsV1Beta1.java
This version generates SBOMs using the CycloneDX schema version 1.6 by default. But also introduces the `--cdx-schema-version` argument to request a different schema version.
> Upgrade domino to 0.0.117 that generates CycloneDX SBOMs using the 1.6 schema by default

- service/src/main/java/org/jboss/sbomer/service/rest/api/v1beta1/GenerationsV1Beta1.java
The payload is no longer `"type": "syft-image"`
> fix(SBOMER-278): Fix typo

- pom.xml
While I agree you should stay compatible with the minor requested by the Operator SDK extension, I don't think it's a good idea to stay on the micro as you are missing all the fixes we are pushing since at the moment the version used here is 3.17.0.
So my advice is: update to the latest micro of the minor branch requested for the Operator SDK.
This is important for #1076 as otherwise, you will have to wait a lot longer to get the fix. Also it's good practice in general.
> chore: update to latest Quarkus micro

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/CycloneDxGenerateOperationCommand.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/processor/DefaultProcessor.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/processor/WorkaroundMissingNpmDependencies.java
- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/service/KojiService.java
- cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/DefaultProcessorTest.java
- cli/src/test/java/org/jboss/sbomer/cli/test/unit/feature/sbom/WorkaroundMissingNpmDependenciesTest.java
- cli/src/test/resources/pnc/mavenBuild.json
- cli/src/test/resources/pnc/mavenBuild2.json
- cli/src/test/resources/pnc/npmDependencies2.json
The operation generation actually doesn't use the Processor where the
addition was taking place previously. This moves it to
CycloneDxGenerateOperationCommand directly.
Also this implementaion doesn't query PNC multiple times for the same
build. And it will not repeat same dependnecy if it comes from multiple
builds.
+ refactor: simplify and optimize component creation for OperationCommand
> fix(SBOMER-142): Really add the NPM dependencies in Operation generation

- e2e/src/test/java/org/jboss/sbomer/test/e2e/rw/ContainerImageGenerationRequestIT.java
- e2e/src/test/resources/requests/skinny-manifest-images.json
This PR adds an additional two images to check with E2E tests, the test input json is now an array as opposed to multiple payloads in separate files.
This test would of originally failing due to alternative image manifest types (non-fat manifest) not being handled by the tekton inspect tasks, this simply tests for regression.
What I'm not sure on 
- If we actually need two additional image? 
- These where the original generations in the bug 
- There is also additional images that where used during testing but removed (internal url references), these fail later for a different reason
- If we only have one image to test is it worth keeping the `@ParameterizedTest`? The only advantage I can think of is if we find something similar in future and a list of images is easier
> test: Additional E2E tests for skinny image manifest type

- e2e/src/test/java/org/jboss/sbomer/test/e2e/rw/ContainerImageGenerationRequestIT.java
Fixes previous skinnyManifest E2E tests
* Rather than verifiy each generates N manifests, check that there is more than zero
* Fix json path for logging
> test: Correct assertion and fix logging output

- service/src/main/java/org/jboss/sbomer/service/feature/s3/S3ClientFacade.java
- service/src/main/java/org/jboss/sbomer/service/feature/s3/S3StorageHandler.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/s3/S3FeatureTest.java
Avoid converting `Path` to/from `String` and `Path` to `File` by using `Path` everywhere. Avoid using regex replacement to create the ID by using the path name directly.
> fix: improve generation of S3 ID

- ui/src/app/api/DefaultSbomerApi.ts
- ui/src/app/components/ManifestsTableTable/ManifestsTable.tsx
- ui/src/app/components/ManifestsTableTable/useSboms.ts
- ui/src/app/types.ts
I am adding menu and search feature to Manifests page.
This planned to be implemented in the Requests page, but with more filters (there is just one additional in Manifests page).
Notes:
- The options of the select (aka 'No filter' and 'Purl') are represented by string, but probably could be represented by enum/type, which could enable us to add more options easily
- Currently, when no filter is applied, the request string contains `query=` with following value of ` ` (nothing), but this the same effect as not having the `query=` at all.
> feat(SBOMER-341): add select and search bar for manifests page

- ui/src/app/components/ManifestsTableTable/ManifestsTable.tsx
- ui/src/app/components/ManifestsTableTable/useManifestsFilters.ts
- ui/src/app/components/ManifestsTableTable/useSboms.ts
New user features:
- Applying filters applies to the URL
- URL is permalink, meaning it can be shared along with the applied filters
- works for URL history (i.e. you can go back and forth to previously applied filters)
Note:
This PR shifts the state management of the page from using useState to using URL state (using useSearchParams) AKA all state of filters ( current queryType, queryValue, pageIndex and pageSize) is now in the URL, meaning this state can be shared using just URL.
This also means that URL history also works with filter states.
Some state management is still left to useState where it made sense, such as with searchBar and visibility of searchButton.
> feat(SBOMER-352): add permalinks to the manifests page filters

- ui/src/app/components/ManifestsTableTable/useManifestsFilters.ts
- ui/src/app/components/RequestEventTable/RequestEventTable.tsx
- ui/src/app/components/RequestEventTable/useRequestEvents.ts
- ui/src/app/components/RequestEventTable/useRequestEventsFilters.ts
- ui/src/app/utils/Utils.ts
User features:
- Permalinks for URL in Requests page filters (same as for Manifests page)
- added restriction that allows only valid QueryType input from URL, if not defaults to "No filter"
> Requests permalink, queryType restriction added

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/CycloneDxGenerateOperationCommand.java
- cli/src/test/java/org/jboss/sbomer/cli/test/integ/feature/sbom/service/PncServiceIT.java
- cli/src/test/resources/mappings/pnc/operation-delivered-artifacts.json
- core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/SbomUtils.java
If given an `AnalyzedArtifact`, add any SPDX license identifers to the licenses of the component. Only licenses for which an SPDX license identifier assertion could be made are listed here.
Since URLs are not unique per identifier, do not add any URL to the licenses of the component. Add any valid absolute URLs to the external references of the component.
Add the full list of licenses, including any licenses which have an SPDX license identifier of `NOASSERTION` or `NONE` to the license evidence of the component. The evidence licenses include URL and source information.
> feat(SBOMER-81): Add license information to components

- ui/src/app/components/GenerationRequestTable/GenerationRequestTable.tsx
- ui/src/app/components/ManifestsTableTable/ManifestsTable.tsx
- ui/src/app/components/RequestEventTable/RequestEventTable.tsx
There was a conflicting link behaviour with ID links on click. Now it is also possible to copy certain values from row without being redirected.
> feat(ui): remove onClick redirect for rows in all tables

- ui/src/app/components/GenerationRequestTable/GenerationRequestTable.tsx
- ui/src/app/components/ManifestsTableTable/ManifestsTable.tsx
- ui/src/app/components/RequestEventTable/RequestEventTable.tsx
Previously the cursor was style 'pointer' (hand pointing) for the each row of the table.
These changes make the cursor style 'auto', meaning we get expected behavior while pointing to certain elements.
These changes could also be implemented via removing the `isClickable` property from `<Tr>` tag, however this wouldn't let us keep a desired feature that highlights the current row on cursor hover.
> Changed cursor behavior to be style 'pointer' only on appropriate elements in UI

- .github/renovate.json
By default, updates are takes major and non-major (minor and patch). adding the separateMinorPatch flag to true separates these types, making it possible to auto-merge only "patch" updates.
> Adding flag in Renovate config to enable auto-merge for "patch" updates

- .github/renovate.json
Changing to use preset `:automergePatch` instead of manually setting automerge.
Removed now unnecessary flags, which are the applied by adding the config preset.
> Adding automergePatch config in Renovate config to fix auto-merge for "patch" updates

- cli/src/main/resources/mapping/stage/product-mapping.yaml
In order to successfully complete e2e tests for Domino we need to disable the new hash calculation feature.
> Disable hashes for domino e2e tests

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/errata/event/comment/CommentAdvisoryOnRelevantEventsListener.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/errata/event/release/ReleaseStandardAdvisoryEventsListener.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/errata/event/release/ReleaseTextOnlyAdvisoryEventsListener.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/errata/event/umb/AdvisoryUmbStatusChangeEventListener.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/errata/event/umb/PncBuildUmbStatusChangeEventListener.java
Now that the events are wrapped in a single class, we need to instruct the listeners to discard non-relevant events.
> fix(SBOMER-381): check the payload types before processing to avoid class cast exceptions

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/errata/ErrataClient.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/kerberos/ErrataKrb5ClientRequestFilter.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/kerberos/PyxisKrb5ClientRequestFilter.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/pyxis/PyxisClient.java
* Add abortOn so we don't retry when we get an unuathorised exception
* Set client filters from config file in a way compatible with static var
> fix(kerberos): kerberos and retry fixes

- ui/src/app/components/RequestEventTable/RequestEventTable.tsx
The results are not paginated, so the pagination for filtered results shouldn't have them.
Also added Caption distinction between filtered and unfiltered results.
> Remove pagination for filtered results on Request page

- hack/build-images-docker.sh
- hack/build-images-minikube.sh
- hack/build-images-podman.sh
- hack/build-ui.sh
- hack/docs-generate.sh
- hack/docs-preview.sh
- hack/generate-release-notes.sh
- hack/internal/build-image.sh
- hack/minikube-delete.sh
- hack/minikube-expose-cache.sh
- hack/minikube-expose-db.sh
- hack/minikube-setup.sh
- hack/minikube-start.sh
- hack/minikube-stop.sh
- hack/run-cli-dev.sh
- hack/run-maven.sh
- hack/run-service-dev.sh
- hack/run-test-e2e.sh
- hack/run-test-integ.sh
- hack/run-test-unit.sh
- hack/run-ui-dev.sh
- hack/sdkman-setup.sh
In order to be more portable across systems, I've changed the shebangs for the scripts within the hack directory to /usr/bin/env instead of /bin/env
This was necessary for me to run the scripts on MacOS
> chore: Change shebangs in hack scripts to /usr/bin/env

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/errata/event/release/ReleaseStandardAdvisoryEventsListener.java
The saveReleaseManifestForDockerGeneration method can be called several times with the same advisoryManifestsRecord which then can lead to updating the same Sbom multiple times. When root purl is regenerated, the first time we can lookup in the originalToRebuiltPurl table the the original root purl of the Sbom, but on subsequent passes, the root purl of the Sbom is already updated, so when we query the originalToRebuilPurl table by the updated root purl, we get null.
> fix: Avoid NPE in release advisory in docker

- service/src/main/java/org/jboss/sbomer/service/nextgen/core/dto/model/EventRecord.java
- service/src/main/java/org/jboss/sbomer/service/nextgen/core/dto/model/GenerationRecord.java
- service/src/main/java/org/jboss/sbomer/service/nextgen/core/rest/SBOMerClient.java
- service/src/main/java/org/jboss/sbomer/service/nextgen/generator/rhrelease/RedHatReleaseGenerator.java
- service/src/main/java/org/jboss/sbomer/service/nextgen/service/config/GeneratorConfigProvider.java
- service/src/main/java/org/jboss/sbomer/service/nextgen/service/rest/v1beta2/EventsApi.java
- service/src/main/java/org/jboss/sbomer/service/nextgen/service/rest/v1beta2/GenerationsApi.java
- service/src/main/java/org/jboss/sbomer/service/nextgen/service/rest/v1beta2/ManifestsApi.java
- service/src/test/java/org/jboss/sbomer/service/test/unit/generator/rhrelease/RedHatReleaseGeneratorTest.java
Introduction of the `/events{id}/generations` endpoint in the API to retrieve generations for a given event.
Similarly, for generation, the `/generation/{id}/manifest` endpoint will be used.
> Optimize API to not pull dependent collections automatically

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/errata/event/release/ReleaseTextOnlyAdvisoryEventsListener.java
- service/src/test/resources/errata/release/textOnly/deliverables/A8342BD50FB9496.json
- Tries to address SBOMER-434
- I updated the test SBOM for deliverables for it to now use redhat: prefixed deliverable-url and deliverable-checksum properties in alignment with the build SBOMs that get produced
- I updated the release sbom building part of the code to now use these redhat: prefixed properties that were also available in Constants
> Update Text-Only Release SBOM builder to use redhat: prefixed properties

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/features/umb/consumer/PncNotificationHandler.java
- service/src/test/java/org/jboss/sbomer/service/test/integ/feature/sbom/messaging/PncBuildTest.java
- service/src/test/resources/mappings/pnc/operation/A6DFVW2SACABC-success.json
- service/src/test/resources/payloads/umb-pnc-del-analysis-body-pending.json
A fix attempt for SBOMER-426.
This PR:
- Introduces a new test case where a Request Event already triggered for the DelA we were waiting for.
- Tries to solve the issue of a DelA result being connected to 2 request events at once when finished
- Looks if pending requests for this DelA operation exists. If so, prioritizes the request event of the pending request and not the one coming from the UMB. 
- After setting the pending request's request event to be the one to use, ignores the UMB one, citing the reasoning and pointing to the request event that was originally waiting for it.
Basically looks at if it the finished operation has an owner already, if so gives that ownership to them.
> Focus on Pending Request Event upon a DelA Finished

- cli/src/main/java/org/jboss/sbomer/cli/feature/sbom/command/CycloneDxGenerateOperationCommand.java
- core/src/main/java/org/jboss/sbomer/core/features/sbom/utils/SbomUtils.java
- core/src/test/java/org/jboss/sbomer/core/test/unit/SbomUtilsTest.java
* Added new method in `SbomUtils`
* `getDistroHashesFromAnalyzedArtifact` takes a AnalyzedArtifact and gets checksums (md5, sha1 & sha256) from AnalyzedDistro
* A getter AnalyzedDistro to cyclonedx `Hash` mapper is provided
* This should allow easier additions of other hashing algorithms in future
* Added simple tests for `getDistroHashesFromAnalyzedArtifact`
* During `CycloneDxGenerateOperationCommand` the main component is created and the hashes are set after the creation
> fix(SBOMER-442): Include checksum for pnc operations

- cli/src/main/resources/mapping/stage/product-mapping.yaml
The current e2e test are failing because one of the product versions of the build ids we use to generate manifests has been changed in PNC. To address this, this PR updates the product version ID to the new one this build uses
> Update product version to the one currently used for pnc id test

- core/src/main/java/org/jboss/sbomer/core/config/request/ErrataAdvisoryRequestConfig.java
- core/src/main/resources/schemas/request/errata-advisory.json
- core/src/test/java/org/jboss/sbomer/core/test/unit/config/RequestConfigSchemaValidatorTest.java
- core/src/test/resources/configs/advisory-force-build.json
- core/src/test/resources/configs/advisory.json
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/errata/event/release/ReleaseStandardAdvisoryEventsListener.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/errata/event/release/ReleaseTextOnlyAdvisoryEventsListener.java
- service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/AdvisoryService.java
- service/src/main/java/org/jboss/sbomer/service/rest/api/v1beta1/GenerationsV1Beta1.java
I added an optional forceBuild so we can invoke build manifest generation for an advisory even if he has already successful previous build manifests.
> Add optional forceBuild field to force the generation of build manifests for a given advisory

- service/pom.xml
- service/src/main/resources/application.yaml
* Add smallrye-metrics to service pom
* Enable metrics for datasource
Once added to the pom.xml metrics can be accessed at http://localhost:8080/q/metrics the metrics we are interested in are `vendor_agroal_*`
> feature(datasource-metrics): To help investigate SBOMER-469 add metrics

- service/src/main/java/org/jboss/sbomer/service/feature/sbom/service/AdvisoryService.java
See https://github.com/project-ncl/sbomer/pull/1727 for a more comprehensive PR which includes wiremock payloads but is based on as yet uncommitted changes, this is the minimal set of changes and as of yet its an untested branch of code
* Remove check for and use of `product_version_text`
* For text only advisories only
* Identifer replaced with CPE
> fix(SBOMER-452): Remove `product_version_text` requirement

- e2e/src/test/java/org/jboss/sbomer/test/e2e/E2EBase.java
- e2e/src/test/java/org/jboss/sbomer/test/e2e/rw/AdvisoryGenerationRequestIT.java
- e2e/src/test/java/org/jboss/sbomer/test/e2e/rw/ContainerImageGenerationRequestIT.java
- e2e/src/test/java/org/jboss/sbomer/test/e2e/rw/StageGenerationRequestIT.java
- service/src/main/java/org/jboss/sbomer/service/rest/api/v1beta1/GenerationsV1Beta1.java
- service/src/main/java/org/jboss/sbomer/service/rest/mapper/V1Beta1Mapper.java
Previously the E2E tests relied upon the generation endpoint returning a generation, this has been changed to return a request to allow asynchronous calling (we cannot wait for a generation to start before responding to client).
These fixes will result in more calls as we also lookup the generations rather than just using the manifest objects referenced in the request payload, this isn't how we expect the API to be used but resulted in minimal changes to the E2E tests
> SBOMER-480 Fix E2E tests
